import { randomUUID } from 'node:crypto'
import { appendFileSync, existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { addServerTemplate, defineNuxtModule, useNuxt } from 'nuxt/kit'

const SESSION_PASSWORD_RE = /^NUXT_SESSION_PASSWORD=/m
const HYPHEN_RE = /-/g

export default defineNuxtModule({
  meta: { name: 'oauth' },
  async setup() {
    const nuxt = useNuxt()

    const clientUri = nuxt.options.dev
      ? 'http://127.0.0.1:3000'
      : process.env.NUXT_PUBLIC_SITE_URL || 'https://skilld.dev'

    addServerTemplate({
      filename: '#oauth/config',
      getContents: () => `export const clientUri = ${JSON.stringify(clientUri)};`,
    })

    if (nuxt.options._prepare || process.env.NUXT_SESSION_PASSWORD) {
      return
    }

    const envPath = join(nuxt.options.rootDir, '.env')
    const hasPassword
      = existsSync(envPath) && SESSION_PASSWORD_RE.test(readFileSync(envPath, 'utf-8'))

    if (!hasPassword) {
      const password = randomUUID().replace(HYPHEN_RE, '')
      nuxt.options.runtimeConfig.sessionPassword = password
      appendFileSync(envPath, `# generated by oauth module\nNUXT_SESSION_PASSWORD=${password}\n`)
    }
  },
})
