/// <reference types="@cloudflare/workers-types" />
import type { H3Event } from 'h3'
import type { TagPayload } from '../../jobs/generate-tags'
import type { RegistrySkill } from '../../utils/skills-registry'
import type { TagSkillRow } from '../../utils/tag-profile'
import { getDB } from '#server/utils/db'
import { cached } from '#shared/server/cache'
import { TAG_BY_SLUG } from '../../jobs/taxonomy'
import { runAfterResponse } from '../../utils/after-response'
import { notBrokenSql } from '../../utils/broken'
import { getGeneratedBatch } from '../../utils/skill-generated'
import { buildIdentifierFtsQuery } from '../../utils/skill-search'
import { parseTagSkillRow } from '../../utils/tag-profile'

import { DERIVED_TAG_MIN_SKILLS, getTagRedirect, isQualityDerivedTag } from '../../utils/tag-quality'

function humanizeSlug(slug: string): string {
  return slug
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

// Tags are regenerated by a batch job, so an hour fresh plus a day served stale
// while one refresh runs is inside how often the counts move.
const DERIVED_TAG_COUNTS_TTL = 60 * 60
const DERIVED_TAG_COUNTS_STALE_TTL = 60 * 60 * 24

/**
 * Skill count per AI-derived tag, only for tags that reach the page threshold.
 *
 * The count was one `json_each` scan of every tags payload per request, about
 * 40K rows each, and the handler cache never held it: an unknown slug 404s, and
 * errors are not cached. That was 177M rows read over 4,463 calls between 11
 * and 13 Sep 2026. One grouped scan per hour answers every slug.
 *
 * A tag under the threshold is left out, and reads as 0, which fails
 * `isQualityDerivedTag` exactly as its real count would. `je.type = 'text'`
 * matches the old `je.value = ?` with a text slug, which never equals a number.
 */
function loadDerivedTagCounts(event: H3Event, db: D1Database): Promise<Record<string, number>> {
  return cached({
    storage: useStorage('cache'),
    key: 'tags:derived-counts:v1',
    ttlSeconds: DERIVED_TAG_COUNTS_TTL,
    staleSeconds: DERIVED_TAG_COUNTS_STALE_TTL,
    compute: async () => {
      const res = await db
        .prepare(
          `SELECT je.value AS tag, COUNT(DISTINCT sg.owner || '/' || sg.repo || '/' || sg.name) AS count
           FROM skill_generated sg, json_each(sg.payload, '$.tags') je
           WHERE sg.kind = 'tags' AND je.type = 'text'
           GROUP BY je.value
           HAVING count >= ?`,
        )
        .bind(DERIVED_TAG_MIN_SKILLS)
        .all<{ tag: string, count: number }>()
      return Object.fromEntries((res.results ?? []).map(row => [row.tag, row.count]))
    },
    schedule: promise => runAfterResponse(event, promise),
  })
}

async function derivedTagCount(event: H3Event, db: D1Database, slug: string): Promise<number> {
  const counts = await loadDerivedTagCounts(event, db)
  return Object.hasOwn(counts, slug) ? counts[slug]! : 0
}

export interface TagOwner {
  owner: string
  count: number
  stars: number
  avatar: string
}

export interface RelatedTag {
  slug: string
  label: string
  count: number
}

export interface TagProfile {
  tag: { slug: string, label: string, description: string }
  totalSkills: number
  totalStars: number
  topOwners: TagOwner[]
  skills: RegistrySkill[]
  relatedTags: RelatedTag[]
  indexable: boolean
  fetchedAt: string
}

const NOT_BROKEN_SQL = notBrokenSql('r')

const TAG_PROFILE_FRESH_SECONDS = 60 * 60 // 1 hour fresh
const TAG_PROFILE_STALE_SECONDS = 60 * 60 * 24 // 1 day of stale-while-revalidate after that
const TAG_PROFILE_SERVE_WINDOW_MS = (TAG_PROFILE_FRESH_SECONDS + TAG_PROFILE_STALE_SECONDS) * 1000

async function buildTagProfile(event: H3Event, slug: string): Promise<TagProfile> {
  const db = getDB(event)
  let tag = TAG_BY_SLUG.get(slug)
  if (!tag) {
    // Long-tail: AI-derived tag must pass the quality gate before earning
    // its own landing page. Anything that fails the gate 404s rather than
    // rendering a thin page that drags domain authority.
    const count = await derivedTagCount(event, db, slug)
    if (!isQualityDerivedTag(slug, count))
      throw createError({ statusCode: 404, message: `Unknown tag: ${slug}` })
    const label = humanizeSlug(slug)
    tag = { slug, label, description: `Skills tagged ${label}.` }
  }
  // Identifier-qualified on purpose: this page answers "which skills *are*
  // this tag", not "which skills mention the word". See buildIdentifierFtsQuery.
  const ftsQuery = buildIdentifierFtsQuery(slug) ?? `"${slug}"*`

  // Skills matching by:
  //   1. FTS on name/owner/repo/display_name/slug (broad, catches `nuxt-ui`, `nuxt`)
  //   2. Exact owner = slug (the official org's repos, e.g. owner='nuxt')
  //   3. AI-classified tags (skill_generated kind='tags')
  // stars/pushed_at/broken_since live on `repos` (post-0034); JOIN explicitly.
  // FTS post-0049 indexes `repo` too, so the tuple match is precise across
  // same-(owner,name) collisions.
  //
  // UNION collects identity candidates before reading Skills. The previous
  // OR walked Skills and expanded generated tag JSON once per Skill.
  // Limit narrow identities before hydrating columns, authors, and repo counts.
  const skillsRes = await db
    .prepare(
      `WITH candidates AS (
         SELECT owner, repo, name FROM skills_fts WHERE skills_fts MATCH ?
         UNION
         SELECT owner, repo, name FROM skills WHERE owner = ?
         UNION
         SELECT sg.owner, sg.repo, sg.name
         FROM skill_generated sg, json_each(sg.payload, '$.tags') je
         WHERE sg.kind = 'tags' AND je.value = ?
       ), tagged AS (
         SELECT s.owner, s.repo, s.name, r.stars
         FROM candidates c
         JOIN skills s ON s.owner = c.owner AND s.repo = c.repo AND s.name = c.name
         JOIN repos r ON r.owner = s.owner AND r.repo = s.repo
         WHERE s.source_resolved = 1 AND ${NOT_BROKEN_SQL}
         ORDER BY r.stars DESC, s.name ASC
         LIMIT 200
       )
       SELECT s.name, s.owner, s.repo, s.display_name, s.slug, tagged.stars, s.like_count,
              s.description, s.rendered_raw_sha256, r.pushed_at, s.modified_at, s.first_seen_at,
              s.rendered_skill_path, s.current_sha, r.default_branch, r.source_owner, r.source_repo,
              o.name AS author_name,
              (SELECT COUNT(*) FROM skills repo_skills
               WHERE repo_skills.owner = tagged.owner
                 AND repo_skills.repo = tagged.repo
                 AND repo_skills.source_resolved = 1) AS repo_skill_count
       FROM tagged
       JOIN skills s ON s.owner = tagged.owner AND s.repo = tagged.repo AND s.name = tagged.name
       JOIN repos r ON r.owner = s.owner AND r.repo = s.repo
       LEFT JOIN owners o ON o.owner = s.owner
       ORDER BY tagged.stars DESC, tagged.name ASC`,
    )
    .bind(ftsQuery, slug, slug)
    .all<TagSkillRow>()

  const parsedSkills = (skillsRes.results ?? []).map(parseTagSkillRow)
  const invalidSkillCount = parsedSkills.filter(result => result._tag === 'invalid').length
  if (invalidSkillCount) {
    emitOperationalEvent(createWideEvent({
      'operation': 'tag-profile-parse',
      'outcome': 'invalid-items-excluded',
      'item.count': invalidSkillCount,
    }))
  }
  const skills: RegistrySkill[] = parsedSkills.flatMap(result =>
    result._tag === 'valid' ? [result.skill] : [],
  )
  if (!skills.length)
    throw createError({ statusCode: 404, message: `No skills tagged ${slug}` })

  const ownerAgg = new Map<string, { count: number, stars: number }>()
  for (const s of skills) {
    const entry = ownerAgg.get(s.owner) ?? { count: 0, stars: 0 }
    entry.count++
    if (s.stars > entry.stars)
      entry.stars = s.stars
    ownerAgg.set(s.owner, entry)
  }

  const topOwners: TagOwner[] = [...ownerAgg.entries()]
    .sort((a, b) => b[1].stars - a[1].stars || b[1].count - a[1].count)
    .slice(0, 8)
    .map(([owner, v]) => ({
      owner,
      count: v.count,
      stars: v.stars,
      avatar: `https://github.com/${owner}.png`,
    }))

  const tagMap = await getGeneratedBatch<TagPayload>(
    db,
    skills.map(s => ({ owner: s.owner, repo: s.repo, name: s.name })),
    'tags',
  )
  const relatedCounts = new Map<string, number>()
  for (const row of tagMap.values()) {
    for (const t of row.payload.tags ?? []) {
      if (t === slug)
        continue
      relatedCounts.set(t, (relatedCounts.get(t) ?? 0) + 1)
    }
  }
  const relatedTags: RelatedTag[] = [...relatedCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([s, count]) => {
      const t = TAG_BY_SLUG.get(s)
      // A redirected tag answers 301, and a page must not link to a 301.
      return t && !getTagRedirect(t.slug) ? { slug: t.slug, label: t.label, count } : null
    })
    .filter((r): r is RelatedTag => r !== null)

  const totalStars = skills.reduce((sum, s) => sum + s.stars, 0)

  // Tag pages are noindex and out of the sitemap. Thin tag listings were part
  // of the scaled-content suppression, and the experiment that started
  // 2026-09-30 (gate 2026-11-11, see trending-admission.ts) keeps only trending
  // Skills in the index. The page still renders for internal navigation. Cull
  // path: restore an editorial `keep = 1` rule and a tags sitemap source in a
  // later change.
  const indexable = false

  const profile: TagProfile = {
    tag: { slug: tag.slug, label: tag.label, description: tag.description },
    totalSkills: skills.length,
    totalStars,
    topOwners,
    skills,
    relatedTags,
    indexable,
    fetchedAt: new Date().toISOString(),
  }

  return profile
}

const getCachedTagProfile = defineCachedFunction(
  (event: H3Event, slug: string, _view: string) => buildTagProfile(event, slug),
  {
    name: 'tag-profile',
    maxAge: TAG_PROFILE_FRESH_SECONDS,
    staleMaxAge: TAG_PROFILE_STALE_SECONDS,
    swr: true,
    getKey: (_event, slug: string, view: string) => `tag-origin:v3:${slug}:${view}`,
    // nitropack 2.13.4 ignores staleMaxAge when swr is on: its default
    // validate only checks value presence, so a permanently failing refresh
    // (for example a tag whose skills were all deleted) would serve the last
    // good profile indefinitely instead of reverting to 404. Enforce the
    // window here: once the entry is older than the fresh hour plus the
    // stale day, validate returns false, nitro skips the stale-serve branch
    // and recomputes synchronously, so the 404 propagates. This also bounds
    // `fetchedAt`, the "Checked GitHub" label on the framework pages, to
    // at most the same window behind any served profile.
    validate: entry =>
      entry.value !== undefined
      && Date.now() - (entry.mtime ?? 0) < TAG_PROFILE_SERVE_WINDOW_MS,
  },
)

export default defineEventHandler(async (event) => {
  const slug = (getRouterParam(event, 'slug') ?? '').toLowerCase()
  const dataView = getQuery(event).view === 'data'

  // Marketing/cluster landing pages own these slugs. Hand off so crawl
  // signal accumulates on the canonical URL instead of splitting. Their SSR
  // data requests opt out explicitly so they can still reuse this profile.
  // Hoisted out of the profile cache: sendRedirect needs the live response,
  // and the lookup is a pure in-memory read.
  const redirect = getTagRedirect(slug)
  if (redirect && !dataView)
    return sendRedirect(event, redirect, 301)

  // The event stays the first argument so nitro registers the background
  // refresh on waitUntil; a non-event first arg would drop SWR
  // revalidation on Workers.
  const profile = await getCachedTagProfile(event, slug, dataView ? 'data' : 'canonical')

  // Same header `defineCachedEventHandler` emitted for this policy (shared
  // freshness plus stale window). etag/304 revalidation is not replicated:
  // this endpoint is consumed through useFetch and the edge policy in the
  // routeRules, neither of which sends conditional requests.
  setResponseHeader(event, 'cache-control', `s-maxage=${TAG_PROFILE_FRESH_SECONDS}, stale-while-revalidate=${TAG_PROFILE_STALE_SECONDS}`)
  return profile
})
