/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=HarnessEnv` (hash: 7a2dedfdaa0af5a67d8baed55aae17df)
interface __BaseEnv_HarnessEnv {
	MODEL: "gemini-3.8-flash";
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	PROOF_TOKEN: string;
	SANDBOX: DurableObjectNamespace<import("./src/index").SkillSandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SkillSandbox";
	}
	interface Env extends __BaseEnv_HarnessEnv {}
}
interface HarnessEnv extends __BaseEnv_HarnessEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MODEL" | "GOOGLE_GENERATIVE_AI_API_KEY" | "PROOF_TOKEN">> {}
}
