/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=HarnessEnv` (hash: ed403e612d246090ec412d137bdb3cc9)
interface __BaseEnv_HarnessEnv {
	PROVIDER: "opencode-go";
	MODEL: "glm-5.3";
	SKILLD_SITE_URL: "https://skilld.dev";
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	PROOF_TOKEN: string;
	ANTHROPIC_API_KEY: string;
	OPENCODE_API_KEY: string;
	GITHUB_APP_ID: string;
	GITHUB_APP_PRIVATE_KEY_PKCS8: string;
	GITHUB_APP_WEBHOOK_SECRET: string;
	SKILLGEN_SITE_TOKEN: string;
	SANDBOX: DurableObjectNamespace<import("./src/index").SkillSandbox>;
	GITHUB_JOBS: DurableObjectNamespace<import("./src/index").GithubJobs>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SkillSandbox" | "GithubJobs";
	}
	interface Env extends __BaseEnv_HarnessEnv {}
}
interface HarnessEnv extends __BaseEnv_HarnessEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROVIDER" | "MODEL" | "SKILLD_SITE_URL" | "GOOGLE_GENERATIVE_AI_API_KEY" | "PROOF_TOKEN" | "ANTHROPIC_API_KEY" | "OPENCODE_API_KEY" | "GITHUB_APP_ID" | "GITHUB_APP_PRIVATE_KEY_PKCS8" | "GITHUB_APP_WEBHOOK_SECRET" | "SKILLGEN_SITE_TOKEN">> {}
}
