/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=HarnessEnv` (hash: b90745979b9e21d3751ed71b1802f853)
interface __BaseEnv_HarnessEnv {
	PROVIDER: "anthropic";
	MODEL: "claude-sonnet-4-6";
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	PROOF_TOKEN: string;
	ANTHROPIC_API_KEY: string;
	SANDBOX: DurableObjectNamespace<import("./src/index").SkillSandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SkillSandbox";
	}
	interface Env extends __BaseEnv_HarnessEnv {}
}
interface HarnessEnv extends __BaseEnv_HarnessEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROVIDER" | "MODEL" | "GOOGLE_GENERATIVE_AI_API_KEY" | "PROOF_TOKEN" | "ANTHROPIC_API_KEY">> {}
}
